package duke.exception;

public enum DukeExceptionType {
    EMPTY_DESCRIPTION,
    INVALID_TASK_FORMAT,
    FULL_TASK_LIST,
    UNKNOWN_INPUT,
    INVALID_TASK_NUMBER,
    WRITE_FILE_ERROR,
    ERROR_LOADING_FILE,
    INVALID_TASK_DATA
}
